---
title: "Quantium Virtual Internship - Retail Strategy and Analytics - Task 1"
mainfont: Roboto
monofont: Consolas
output:  
  pdf_document:     
    df_print: default    
    highlight: tango    
    keep_tex: yes    
    latex_engine: xelatex
header-includes:  
  \usepackage{fvextra}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---

```{r setup, include=FALSE}
# set options for R markdown knitting
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(linewidth=80)
```

```{r knitr line wrap setup, include=FALSE}
# set up line wrapping in MD knit output
library(knitr)
hook_output = knit_hooks$get("output")
knit_hooks$set(output = function(x, options)
{    
  # this hook is used only when the linewidth option is not NULL    
  if (!is.null(n <- options$linewidth))     
  {        
    x = knitr:::split_lines(x)        
    # any lines wider than n should be wrapped        
    if (any(nchar(x) > n))             
      x = strwrap(x, width = n)        
    x = paste(x, collapse = "\n")    
  }    
  hook_output(x, options)
})
```

```{r 0 Load Libraries, results = 'hide'}
#### Example code to install packages
#install.packages("data.table")
#install.packages("ggplot2")
#install.packages("ggmosaic")
#install.packages("readr")

#### Load required libraries
library(data.table)
library(ggplot2)
library(ggmosaic)
library(readr)

#### Point the filePath to where you have downloaded the datasets to and 
#### assign the data files to data.tables

# over to you! fill in the path to your working directory. If you are on a Windows machine, you will need to use forward slashes (/) instead of backshashes (\)

#filePath <- "C:\Users\gaura\Desktop\Quantium"
#transactionData <- fread(paste0(filePath,"QVI_transaction_data.csv"))
#customerData <- fread(paste0(filePath,"QVI_purchase_behaviour.csv"))
transactionData <- read.csv("QVI_transaction_data.csv", header= TRUE)
customerData <- read.csv("QVI_purchase_behaviour.csv", header= TRUE)
```

```{r Examining transaction data}
#### Examine transaction data
str(transactionData)
head(transactionData)
```

```{r Convert DATE to date format}
#### Convert DATE column to a date format
#### A quick search online tells us that CSV and Excel integer dates begin on 30 Dec 1899
transactionData$DATE <- as.Date(transactionData$DATE, origin = "1899-12-30")
```

```{r Summary of PROD_NAME}
#### Examine PROD_NAME# Over to you! Generate a summary of the PROD_NAME column.
summary(transactionData$PROD_NAME)
```

```{r Further examine PROD_NAME}
#### Examine the words in PROD_NAME to see if there are any incorrect entries 
#### such as products that are not chips
productWords <- data.table(unlist(strsplit(unique(transactionData[, "PROD_NAME"]), " ")))
setnames(productWords, 'words')
```

```{r}
# Over to you! Remove digits, and special characters, and then sort the distinct words by frequency of occurrence.
#### Removing digits
productWords[,SPECIAL := grepl("[[:digit:]]",words)]
productWords <- productWords[SPECIAL == FALSE,][,SPECIAL := NULL]
#### Removing special characters
productWords[,SPECIAL := grepl("[[:punct:]]",words)]
productWords <- productWords[SPECIAL == FALSE,][,SPECIAL := NULL]
#### Let's look at the most common words by counting the number of times a word appears and 
productWords[words == ""] <- NA
productWords <- productWords[complete.cases(productWords),]
#### sorting them by this frequency in order of highest to lowest frequency
productWords <- data.frame(sort(table(productWords),decreasing = TRUE))
```

```{r}
#### Remove salsa products
transactionData<- data.table(transactionData)
transactionData[, SALSA := grepl("salsa", tolower(PROD_NAME))]
transactionData <- transactionData[SALSA == FALSE, ][, SALSA := NULL]
```

```{r initial summary}
#### Summarise the data to check for nulls and possible outliers# Over to you!
summary(transactionData)
sum(is.na(transactionData))
```

```{r }
#### Filter the dataset to find the outlier
# Over to you! Use a filter to examine the transactions in question.
outlier <- transactionData[PROD_QTY == 200,]
```

```{r}
#### Let's see if the customer has had other transactions# Over to you! Use a filter to see what other transactions that customer made.

```

```{r}
#### Filter out the customer based on the loyalty card number# Over to you!
outlierTransactions <- transactionData[LYLTY_CARD_NBR == 226000,]
#### Re-examine transaction data# Over to you!
numberOfTransactionsByDate <- data.frame(sort(table(transactionData$DATE),decreasing = TRUE ))
setnames(numberOfTransactionsByDate,c('date','freq'))
numberOfTransactionsByDate<-numberOfTransactionsByDate[order(as.Date(numberOfTransactionsByDate$date)),]
```

```{r}
#### Count the number of transactions by date
# Over to you! Create a summary of transaction count by date.
unique(transactionData$DATE)
summary(transactionData$DATE)
```

```{r fig.align = "center"}
#### Create a sequence of dates and join this the count of transactions by date
# Over to you - create a column of dates that includes every day from 1 Jul 2018 to 30 Jun 2019, and join it onto the data to fill in the missing day.
seqOfDates <- data.table(seq(as.Date('2018-07-01'),as.Date('2019-06-30'),by = 1))
setnames(seqOfDates,"date")
seqOfDates$date <- as.factor(seqOfDates$date)
class(seqOfDates$date)
class(numberOfTransactionsByDate$date)
transactions_by_day <- merge (x = seqOfDates, y = numberOfTransactionsByDate, by="date", all.x = TRUE)
transactions_by_day[is.na(transactions_by_day)] <- 0
transactions_by_day$date <- as.Date(transactions_by_day$date)

#### Setting plot themes to format graphs
theme_set(theme_bw())
theme_update(plot.title = element_text(hjust = 0.5))

#### Plot transactions over time
ggplot(transactions_by_day, aes(x = date, y = freq)) +
 geom_line() +
 labs(x = "Day", y = "Number of transactions", title = "Transactions over time") +
 scale_x_date(breaks = "1 month") +
 theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

```{r fig.align = "center"}
#### Filter to December and look at individual days
# Over to you - recreate the chart above zoomed in to the relevant dates.
december <- transactions_by_day[transactions_by_day$date >= as.Date("2018-12-01") & transactions_by_day$date <= as.Date("2018-12-31"),]
ggplot(december,aes(x=date,y= freq)) +
  geom_line() + 
  labs(x = "Day", y ="Number of transactions",title="Transactions over time (December)")+
  scale_x_date(breaks = "1 day") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

```{r Create pack size}
#### Pack size
#### We can work this out by taking the digits that are in PROD_NAMEtransactionData[, PACK_SIZE := parse_number(PROD_NAME)]
transactionData[, PACK_SIZE := parse_number(PROD_NAME)]

#### Always check your output
#### Let's check if the pack sizes look sensible 
transactionData[, .N, PACK_SIZE][order(PACK_SIZE)]
```

```{r }
#### Let's plot a histogram of PACK_SIZE since we know that it is a categorical variable and not a continuous variable even though it is numeric.

# Over to you! Plot a histogram showing the number of transactions by pack size.
ggplot(transactionData,aes(x=PACK_SIZE) )+
  geom_histogram(binwidth = 10,color="black",fill="lightblue") +scale_x_discrete() +
  labs(x = "Pack Sizes", y ="Frequency",title="Histogram of Pack Sizes")+scale_color_brewer(palette="Dark2")+geom_density(alpha=.2, fill="#FF6666") #### mean and standard deviation of pack sizes 
mean(transactionData$PACK_SIZE)
sd(transactionData$PACK_SIZE)
```

```{r Create brand name}
#### Brands
# Over to you! Create a column which contains the brand of the product, by extracting it from the product name.
transactionData$BRAND_NAME <- sub('(^\\w+)\\s.+','\\1',transactionData$PROD_NAME)

#### Checking brands
# Over to you! Check the results look reasonable. 
```

```{r Clean brand names}
#### Clean brand names
transactionData[BRAND_NAME == "RED", BRAND_NAME := "RRD"]
transactionData[BRAND_NAME == "GRAIN", BRAND_NAME := "GrnWves"]
transactionData[BRAND_NAME == "INFZNS", BRAND_NAME := "Infuzions"]
transactionData[BRAND_NAME == "WW", BRAND_NAME := "Woolworths"]
transactionData[BRAND_NAME == "SNBTS", BRAND_NAME := "Sunbites"]

# Over to you! Add any additional brand adjustments you think may be required.

#### Check again
# Over to you! Check the results look reasonable. 
brands <- data.frame(sort(table(transactionData$BRAND_NAME),decreasing = TRUE ))
setnames(brands,c("BRAND","freq"))
ggplot(brands,aes(x=BRAND,y= freq,fill=BRAND)) +
  geom_bar(stat="identity",width = 0.5) + 
  labs(x = "Brands", y ="Frequency",title="Distribution Of Brand Purchases")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

```{r 1 Exploratory data analysis}
#### Examining customer data
# Over to you! Do some basic summaries of the dataset, including distributions of any key columns.
summary(customerData)
sum(is.na(customerData))
lifestageCategory <- data.frame(sort(table(customerData$LIFESTAGE),decreasing = TRUE ))
setnames(lifestageCategory,c("lifestage","freq"))
ggplot(lifestageCategory,aes(x=lifestage,y= freq,fill=lifestage)) +
  geom_bar(stat="identity",width = 0.5) + 
  labs(x = "lifestage", y ="frequency",title="Distribution Of Customers Over Lifestages")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+scale_fill_brewer(palette="Dark2")
premiumCustomerType <- data.frame(sort(table(customerData$PREMIUM_CUSTOMER),decreasing = TRUE ))
setnames(premiumCustomerType,c("premium_customer_type","freq"))
ggplot(premiumCustomerType,aes(x=premium_customer_type,y= freq,fill=premium_customer_type)) +
  geom_bar(stat="identity",width = 0.5) + 
  labs(x = "lifestage", y ="frequency",title="Distribution Of Customers Over Premium Types")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+scale_fill_brewer(palette="Dark2")
```

```{r }
#### Merge transaction data to customer data
data <- merge(transactionData, customerData, all.x = TRUE)
```

```{r Check for missing customer details}
# Over to you! See if any transactions did not have a matched customer.
sum(is.na(data))
```

```{r Code to save dataset as a csv}
fwrite(data, paste0("QVI_data.csv"))
```

```{r  fig.width = 10, fig.align = "center"}
#### Total sales by LIFESTAGE and PREMIUM_CUSTOMER
# Over to you! Calculate the summary of sales by those dimensions and create a plot.
totalSalesByLifestage <- aggregate(data$TOT_SALES, by=list(LIFESTAGE=data$LIFESTAGE),FUN=sum)
setnames(totalSalesByLifestage,c("Lifestage","Total_Sales"))
totalSalesByLifestage<-totalSalesByLifestage[order(totalSalesByLifestage$Total_Sales,decreasing = FALSE),]
ggplot(totalSalesByLifestage,aes(x=reorder(Lifestage,-Total_Sales),y= Total_Sales,fill=Lifestage)) +
  geom_bar(stat="identity",width = 0.5) + 
  labs(x = "lifestage", y ="Total Sales",title="Total Sales By Lifestage")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+scale_fill_brewer(palette="Dark2")

totalSalesByPremium <- aggregate(data$TOT_SALES, by=list(LIFESTAGE=data$PREMIUM_CUSTOMER),FUN=sum)
setnames(totalSalesByPremium,c("Premium_Customer","Total_Sales"))
totalSalesByPremium<-totalSalesByPremium[order(totalSalesByPremium$Total_Sales,decreasing = FALSE),]
ggplot(totalSalesByPremium,aes(x=reorder(Premium_Customer,-Total_Sales),y= Total_Sales,fill=Premium_Customer)) +
  geom_bar(stat="identity",width = 0.5) + 
  labs(x = "Premium Customer", y ="Total Sales",title="Total Sales By Premium Customer")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+scale_fill_brewer(palette="Dark2")

totalSalesByPremiumAndLifestage <- aggregate(.~LIFESTAGE+PREMIUM_CUSTOMER, data = data[,c("LIFESTAGE","PREMIUM_CUSTOMER","TOT_SALES")] , sum)
totalSalesByPremiumAndLifestage$Lifestage_Premium <- paste(totalSalesByPremiumAndLifestage$LIFESTAGE,totalSalesByPremiumAndLifestage$PREMIUM_CUSTOMER)
totalSalesByPremiumAndLifestage <- totalSalesByPremiumAndLifestage[,c("Lifestage_Premium","TOT_SALES")]
ggplot(totalSalesByPremiumAndLifestage,aes(x=reorder(Lifestage_Premium,-TOT_SALES),y= TOT_SALES,fill=Lifestage_Premium)) +
  geom_bar(stat="identity",width = 0.5) + 
  labs(x = "Lifestage and Premium", y ="Total Sales",title="Total Sales By Lifestage By Premium")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

```{r fig.width = 10, fig.align = "center"}
#### Number of customers by LIFESTAGE and PREMIUM_CUSTOMER
# Over to you! Calculate the summary of number of customers by those dimensions andcreate a plot.
numberOfCustomersByLifestageByPremium <- data.frame(paste(customerData$LIFESTAGE,customerData$PREMIUM_CUSTOMER))
numberOfCustomersByLifestageByPremium <- data.frame(sort(table(numberOfCustomersByLifestageByPremium),decreasing = TRUE ))
setnames(numberOfCustomersByLifestageByPremium,c("Lifestage_Premium","freq"))
ggplot(numberOfCustomersByLifestageByPremium,aes(x=Lifestage_Premium,y = freq,fill=Lifestage_Premium)) +
  geom_bar(stat="identity",width = 0.5) + 
  labs(x = "Lifestage and Premium", y ="Number of Customers",title="Number of Customers By Lifestage By Premium")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

```{r fig.width = 10, fig.align = "center"}
#### Average number of units per customer by LIFESTAGE and PREMIUM_CUSTOMER
# Over to you! Calculate and plot the average number of units per customer by thosetwo dimensions.
averageNumberOfUnits <- data.table(data[,c("LIFESTAGE","PREMIUM_CUSTOMER","PROD_QTY")])
averageNumberOfUnits$Lifestage_Premium <-  data.table(paste(data$LIFESTAGE,data$PREMIUM_CUSTOMER))
setnames(averageNumberOfUnits,c("Lifestage","premium","prod_qty","Lifestage_Premium"))
averageNumberOfUnits<- averageNumberOfUnits[,c("Lifestage_Premium","prod_qty")]
setnames(averageNumberOfUnits,c("Lifestage_Premium","PROD_QTY"))
averageNumberOfUnits <- aggregate(.~Lifestage_Premium, data = averageNumberOfUnits[,c("Lifestage_Premium","PROD_QTY")] , mean)
ggplot(averageNumberOfUnits,aes(x=reorder(Lifestage_Premium,-PROD_QTY),y= PROD_QTY,fill=Lifestage_Premium)) +
  geom_bar(stat="identity",width = 0.5) + 
  labs(x = "Lifestage and Premium", y ="Average Units Bought",title="Average Units Per Customer Segment ")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

```{r fig.width = 10, fig.align = "center"}
#### Average price per unit by LIFESTAGE and PREMIUM_CUSTOMER
# Over to you! Calculate and plot the average price per unit sold (average sale price) by those two customer dimensions.
averagePrice <- data.table(data[,c("LIFESTAGE","PREMIUM_CUSTOMER","PROD_QTY","TOT_SALES")])
averagePrice$Lifestage_Premium <-  data.table(paste(data$LIFESTAGE,data$PREMIUM_CUSTOMER))
setnames(averagePrice,c("Lifestage","premium","prod_qty","TOT_SALES","Lifestage_Premium"))
averagePrice<- averagePrice[,c("Lifestage_Premium","prod_qty","TOT_SALES")]
averagePrice <- aggregate(.~Lifestage_Premium, data = averagePrice , FUN= sum )
averagePrice$averagePricePerUnit <- averagePrice$TOT_SALES / averagePrice$prod_qty
ggplot(averagePrice,aes(x=reorder(Lifestage_Premium,-averagePricePerUnit),y= averagePricePerUnit,fill=Lifestage_Premium)) +
  geom_bar(stat="identity",width = 0.5) + 
  labs(x = "Lifestage and Premium", y ="Average Price Per Unit Bought",title="Average Price Per Unit Per Customer Segment ")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

```{r}
#### Perform an independent t-test between mainstream vs premium and budget midage and 
#### young singles and couples
# Over to you! Perform a t-test to see if the difference is significant.
mainstreamYoungSingleCouples <- data.table(data)
mainstreamYoungSingleCouples$Lifestage_Premium <-  data.table(paste(data$LIFESTAGE,data$PREMIUM_CUSTOMER))
mainstreamYoungSingleCouples <- mainstreamYoungSingleCouples[Lifestage_Premium =='YOUNG SINGLES/COUPLES Mainstream']
mainstreamYoungSingleCouplesBrandFreq <- data.frame(sort(table(mainstreamYoungSingleCouples$BRAND_NAME),decreasing = TRUE ))
setnames(mainstreamYoungSingleCouplesBrandFreq,c('BRAND_NAME','freq'))
ggplot(mainstreamYoungSingleCouplesBrandFreq,aes(x=BRAND_NAME ,y=freq ,fill=BRAND_NAME)) +
  geom_bar(stat="identity",width = 0.5) + 
  labs(x = "Brands", y ="Count",title="Mainstream - Young Single/Couples Brand Purchases")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

```{r fig.align = "center"}
#### Deep dive into Mainstream, young singles/couples 

# Over to you! Work out of there are brands that these two customer segments prefermore than others. You could use a technique called affinity analysis or a-priori analysis (or any other method if you prefer)
is.na(mainstreamYoungSingleCouples)
ggplot(mainstreamYoungSingleCouples,aes(x=PACK_SIZE) )+
  geom_histogram(binwidth = 10,color="black",fill="lightblue") +
  labs(x = "Pack Sizes", y ="Frequency",title="Histogram of Pack Sizes For Young Single/Couples- Mainstream")+scale_color_brewer(palette="Dark2")+geom_density(alpha=.2, fill="#FF6666")+
  scale_x_continuous(breaks = seq(0, 400, 10), limits = c(0,400))

mean(mainstreamYoungSingleCouples$PACK_SIZE)
sd(mainstreamYoungSingleCouples$PACK_SIZE)
```

```{r fig.align = "center"}
#### Preferred pack size compared to the rest of the population
# Over to you! Do the same for pack size.
segment1 <- data[LIFESTAGE == "YOUNG SINGLES/COUPLES" & PREMIUM_CUSTOMER == "Mainstream",]
other <- data[!(LIFESTAGE == "YOUNG SINGLES/COUPLES" & PREMIUM_CUSTOMER == "Mainstream"),]
quantity_segment1 <- segment1[, sum(PROD_QTY)]
quantity_other <- other[, sum(PROD_QTY)]
quantity_other_by_size <- other[, .(other = sum(PROD_QTY)/quantity_other), by = PACK_SIZE]
quantity_segment1_by_pack <- segment1[, .(targetSegment = sum(PROD_QTY)/quantity_segment1), by = PACK_SIZE]
quantity_other_by_pack <- other[, .(other = sum(PROD_QTY)/quantity_other), by = PACK_SIZE]
pack_proportions <- merge(quantity_segment1_by_pack, quantity_other_by_pack)[, affinityToPack := targetSegment/other]
pack_proportions[order(-affinityToPack)]
```